# SPDX-License-Identifier: Unlicense OR 0BSD
on: [push]

jobs:
  hxltm-testum:
    runs-on: ubuntu-latest
    name: hxltm-extras-action ego testum
    steps:

      # @see https://github.com/actions/checkout
      - name: Checkout the git repository to the actions temporary host runner
        uses: actions/checkout@v2
        # with:
        #   path: main

      #### bin --help __________________________________________________________
      - name: "compgen -c"
        uses: ./
        continue-on-error: true
        with:
          bin: "compgen "
          args: "-c"

      - name: "find /usr/local/bin/ -executable -type f"
        uses: ./
        continue-on-error: true
        with:
          bin: "find"
          args: "/usr/local/bin/ -executable -type f"

      # http://mywiki.wooledge.org/ParsingLs, bad idea
      - name: "ls /usr/local/bin/"
        uses: ./
        continue-on-error: true
        with:
          bin: "ls"
          args: "/usr/local/bin/"

      - name: "csvstat --help"
        uses: ./
        with:
          bin: "csvstat"
          args: "--help"

      - name: "csv2po --help"
        uses: ./
        with:
          bin: "csv2po"
          args: "--help"

      # cd /workspace/git/fititnt/hxltm-action-example/data/verum/TICO-19/terminologies-google
      # mlr --csv cat data/verum/TICO-19/terminologies-google/*.csv > data/verum/TICO-19/terminologies-google.csv
      # mlr --csv cat data/verum/TICO-19/terminologies-facebook/*.csv > data/verum/TICO-19/terminologies-facebook.csv


      ### RU
      # hxltmdexml --agendum-linguam eng-Latn@en,rus-Cyrl@ru data/verum/TICO-19/translation-memories/all.en-ru.tmx data/verum/TICO-19/translation-memories-hxltm/all.en-ru.tm.hxl.csv

      ### FRA
      # hxltmdexml --agendum-linguam eng-Latn@en,fra-Latn@fr data/verum/TICO-19/translation-memories/all.en-fr.tmx data/verum/TICO-19/translation-memories-hxltm/all.en-fr.tm.hxl.csv

      ### HIN
      # hxltmdexml --agendum-linguam eng-Latn@en,hin-Deva@hi data/verum/TICO-19/translation-memories/all.en-hi.tmx data/verum/TICO-19/translation-memories-hxltm/all.en-hi.tm.hxl.csv

      # hxltmdexml --agendum-linguam eng-Latn@en,por-Latn@pt data/verum/TICO-19/translation-memories/all.en-pt-BR.tmx

      # hxltmdexml --agendum-linguam eng-Latn@en data/verum/TICO-19/translation-memories/all.en-pt-BR.tmx data/verum/TICO-19/translation-memories-hxltm/all.en.tm.hxl.csv

      # hxltmdexml --agendum-linguam eng-Latn@en,por-Latn@pt data/verum/TICO-19/translation-memories/all.en-pt-BR.tmx data/verum/TICO-19/translation-memories-hxltm/all.en-pt-BR.tm.hxl.csv

      # hxltmdexml --agendum-linguam eng-Latn@en,por-Latn@pt,rus-Cyrl@ru data/verum/TICO-19/translation-memories/all.en-ru.tmx data/verum/TICO-19/translation-memories-hxltm/all.en-ru.tm.hxl.csv

      # hxltmdexml --agendum-linguam eng-Latn@en,por-Latn@pt,rus-Cyrl@ru,spa-Latn@es,spa-Latn@es@419 data/verum/TICO-19/translation-memories/all.en-es-419.tmx data/verum/TICO-19/translation-memories-hxltm/all.en-es-419.tm.hxl.csv

      # hxltmdexml --agendum-linguam eng-Latn@en,por-Latn@pt,rus-Cyrl@ru,spa-Latn@es,spa-Latn-419@es-419 data/verum/TICO-19/translation-memories/all.en-es-419.tmx data/verum/TICO-19/translation-memories-hxltm/all.en-es-419.tm.hxl.csv

      # data/verum/TICO-19/translation-memories-hxltm/all.en.tm.hxl.csv


      # cp data/verum/TICO-19/translation-memories-hxltm/all.en.tm.hxl.csv data/verum/TICO-19/translation-memories.tm.hxl.csv

      # hxlmerge --keys='#item+conceptum+codicem' --tags='#item' --merge data/verum/TICO-19/translation-memories.tm.hxl.csv data/verum/TICO-19/translation-memories-hxltm/all.en.tm.hxl.csv

      # hxlmerge --keys='#item+conceptum+codicem' --tags='#item' --merge data/verum/TICO-19/translation-memories.tm.hxl.csv data/verum/TICO-19/translation-memories-hxltm/all.en.tm.hxl.csv data/verum/TICO-19/translation-memories-hxltm/all.en-ru.tm.hxl.csv

      # - name: "csv2po --help"
      #   uses: ./
      #   continue-on-error: true
      #   with:
      #     bin: "csv2po"
      #     args: "--help"

      #### Get additional test data and put on data/ ___________________________
      - run: wget https://github.com/fititnt/hxltm-action-example/archive/refs/heads/main.zip
      - run: unzip main.zip
      - run: cp -r hxltm-action-example-main/data/ data/
      - run: find data/

      # #### Quick general tests _________________________________________________
      # - name: "hxltmcli --objectivum-TBX-Basim data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/exemplum/resultatum/de-hxltm/hxltm-exemplum-linguam.tbx"
      #   uses: ./
      #   continue-on-error: true
      #   with:
      #     bin: "hxltmcli"
      #     args: "--objectivum-TBX-Basim"
      #     infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
      #     outfile: data/exemplum/resultatum/de-hxltm/hxltm-exemplum-linguam.tbx
      #     working_languages: |
      #       arb-Arab@ar
      #       por-Latn@pt
      #       hin-Deva@hi
      #     auxiliary_languages: |
      #       eng-Latn@en

      # - name: "(1) hxltmcli --objectivum-formulam data/README.🗣️.md --objectivum-linguam eng-Latn@en data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/README.eng-Latn.md"
      #   uses: ./
      #   continue-on-error: true
      #   with:
      #     bin: "hxltmcli"
      #     args: |
      #       --objectivum-formulam data/README.🗣️.md
      #       --objectivum-linguam eng-Latn@en
      #     infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
      #     outfile: data/README.eng-Latn.md

      # - name: "(2) hxltmcli --objectivum-formulam data/README.🗣️.md --objectivum-linguam eng-Latn@en data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/README.eng-Latn.md"
      #   uses: ./
      #   continue-on-error: true
      #   with:
      #     bin: "hxltmcli"
      #     infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
      #     outfile: data/README.eng-Latn.md
      #     export_ad_hoc_template: data/README.🗣️.md
      #     target_language: eng-Latn@en


      #   #### Upload artifacts for inspection ___________________________________
      # # @see https://github.com/actions/upload-artifact
      # - uses: actions/upload-artifact@v2
      #   # continue-on-error: true
      #   # https://github.com/nektos/act#skipping-steps
      #   if: ${{ !env.ACT }}
      #   with:
      #     name: objectivum
      #     path: tests/result/

      # #### Upload results ______________________________________________________
      # # @see https://github.com/actions/upload-artifact
      # - uses: actions/upload-artifact@v2
      #   if: ${{ !env.ACT }}
      #   # continue-on-error: true
      #   with:
      #     name: data
      #     path: data/
      #     retention-days: 5
